# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/testNbdev',
                'doc_host': 'https://PirateBear.github.io',
                'git_url': 'https://github.com/PirateBear/testNbdev',
                'lib_path': 'testNbdev'},
  'syms': {'testNbdev.core': {'testNbdev.core.foo': ('core.html#foo', 'testNbdev/core.py')}}}
